bopwebapi/bopwebapi/urls.py
from django.contrib import admin
from django.urls import path,include
from posts import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',views.PostListView.as_view(),name='posts'),
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('users/',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bopwebapi/posts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home,PostListView,PostFormView,PostDetailView,add_comment_to_post,graph_view,PostUpdateView
from posts import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'posts'

urlpatterns = [
    path('',views.PostListView.as_view(),name='posts'),
    path('all/',views.PostListView.as_view(),name='posts'),
    path('new/',views.PostFormView.as_view(),name='create-post'),
    path('<int:pk>/',views.PostDetailView.as_view(),name='post-detail'),
    path('<int:pk>/comment',views.add_comment_to_post,name='add-comment'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update-post'),
    path('stats/',views.graph_view,name='graph'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bopwebapi/users/urls.py
from django.contrib import admin
from django.urls import path,include
from users import views
from .views import user_logout,register,profile_update,view_profile,PostLikeRedirect
from .forms import UserProfileInfoForm
from users import forms
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='user-login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.register,name='register'),
    path('profile/update/',views.profile_update,name='profile-update'),
    path('account/',views.view_profile,name='view_profile'),
    path('account/<pk>/',views.view_profile,name='view_profile_with_pk'),
    path('account/<pk>/subscribe',views.PostLikeRedirect.as_view(),name='subscribe'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

bopwebapi/posts/models.py
from django.db import models
from PIL import Image
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.urls import reverse
from django.utils import timesince,timezone
from django.contrib.auth.models import User
from .validators import validate_file_extension
# Create your models here.

class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)  # change eventually to logged in user
    description = models.TextField(max_length=60)
    image = ProcessedImageField(upload_to='post_images',
                                        processors=[ResizeToFill(350,350)],
                                        format='JPEG',
                                        default='default.jpg',
                                        options={'quality':60},
                                        )
    thumbnail = ProcessedImageField(upload_to='post_thumbnails',
                                        processors=[ResizeToFill(1280,720)],
                                        format='JPEG',
                                        options={'quality':60},
                                        null = True,
                                        blank = True,
                                        )
    views = models.IntegerField(default=0)                                    
    video = models.FileField(default='default.mp4',upload_to="post_images", validators=[validate_file_extension])                                    
    published_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)

    def __str__(self):
        return self.description
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
    
    def  get_absolute_url(self):
        return reverse('posts:posts')

class Comment(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField(max_length=300)
    post = models.ForeignKey('posts.Post',on_delete=models.CASCADE,related_name='comments')
    

    def __str__(self):
        return self.text

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

bopwebapi/posts/forms.py
from django import forms
from .models import Post,Comment
from .views import *


class PostForm(forms.ModelForm):
    def __init__(self,*args,**kwargs):
        super(PostForm,self).__init__(*args,**kwargs)
        self.fields['video'].required = True
        self.fields['thumbnail'].required = True
        self.fields['description'].required = True
    
    class Meta:
        model = Post
        fields = ['video','thumbnail','description']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

    def __init__(self,*args,**kwargs):
        super(CommentForm,self).__init__(*args,**kwargs)

bopwebapi/posts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Post,Comment
from posts import models
from .forms import PostForm,CommentForm
from django.views.generic import ListView,DetailView,UpdateView,DeleteView,RedirectView,CreateView
# Create your views here.


def home(request):
    return render(request,'posts/index.html')

class PostListView(ListView):
    template_name = 'posts/post_list.html'
    model = Post
    def get(self,request):
        posts = Post.objects.all()
        context = {'posts':posts}
        return render(request,self.template_name,context)

    def get_queryset(self):
        return Post.objects.all()

class PostDetailView(DetailView):
    model = Post
    template_name = 'posts/post_detail.html'


class PostUpdateView(UpdateView):
    model = Post
    fields = ['description','thumbnail']
    redirect_field_name = 'posts/post_list.html/'
    template_name = 'posts/post_update.html'

    def test_func(self):
        if request.user == post.author:
            return True
        else:
            return False



class PostFormView(CreateView):
    model = Post
    template_name = 'posts/post_form.html'
    redirect_field_name = 'posts/post_list.html/'
    form_class = PostForm

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)

def add_comment_to_post(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('posts:post-detail',pk=post.pk)
    else:
        form = CommentForm
    return render(request,'posts/comment_form.html',{'form':form})   

def get_queryset(self):
    # return Comment.objects.filter(created_date__lte=timezone.now()).order_by('-created_date')
    return Comment.objects.all()



def graph_view(request):
    import matplotlib.pyplot as plt

    page_views = [23,495,958,948,2012,942]
    post_likes = [8,128,491,821,1892,213]

    lines = plt.plot(page_views,post_likes)
    plt.grid(True)
    plt.setp(lines,color=(1,.4,.4),marker='o',mec=(62/255, 15/255, 138/255),mew=(1.25),picker=(0.4))

    plt.xlabel('Page Views')
    plt.ylabel('Post Likes')
    plotgraph1 = plt.savefig(f'media/post_images/filename{request.user}.png')
    plt.show()

    return render(request,'posts/graph.html',{'plt':plotgraph1})

bopwebapi/posts/templates/posts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bop!</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link href="https://vjs.zencdn.net/7.5.5/video-js.css" rel="stylesheet" />

    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
</head>
<body>
        <div id="mySidenav" class="sidenav">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
                
                {% if user.is_authenticated %}
                <img class="profile-image-navbar-nav" src="{{ request.user.profile.image.url }}" alt="profile image">
                <a href="{% url 'users:view_profile' %}">{{ request.user }}</a>
        {% else %}
        <a class="register-button-homescreen" href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:user-login' %}" class="login-button-homescreen">Login</a>
        
        {% endif %}
                
                <a href="#">Account Settings</a>
                <a href="#">Playlists</a>
                <!-- <a href="#">Logout</a> -->
              </div>
              <div id="container">
              <div class="navbar-home-nav">
        <i onclick="openNav()" style="transform: translateY(-2rem); margin-left: 2rem;" class="fas fa-bars"></i>
        <a href="{% url 'posts:posts' %}">
        <img style="margin-left: 1rem;" draggable="false" style="user-select: none;" height="85" width="auto" class="navbar-logo-header" src="{% static 'images/bop-logo.png' %}" alt="Bop's Logo">
        </a>

        <div style="transform: translateY(1.5rem);" class="navbar-right-align">
          <div class="dropdown">
            {% if user.is_authenticated %}
        <img style=" margin-right: 2rem; border-radius: 50%;" class="profile-image-small-right-float dropbtn" src="{{ request.user.profile.image.url }}" alt="profile image" height="40" width="40">
        <div style="transform: translateX(-75%);" class="dropdown-content">
            <a href="{% url 'users:view_profile' %}">Profile</a>
            <a href="{% url 'users:profile-update' %}">Account Settings</a>
            <a href="#">Subscriptions</a>
          </div>
        </div>
        {% else %}
        <a class="register-button-homescreen" href="{% url 'users:register' %}">Register</a>
    <a href="{% url 'users:user-login' %}" class="login-button-homescreen">Login</a>
        
        {% endif %}
        </div>
    </div>
    </div>
    {% block content %}{% endblock %}
  
    

    <script>
            function openNav() {
              document.getElementById("mySidenav").style.width = "300px";
             // document.getElementById("container").style.backgroundColor = "black";
              //document.getElementById("container").style.opacity = "0.3";
              //document.getElementById("container").style.boxShadow = "0 0 3px black";
            }
            
            function closeNav() {
              document.getElementById("mySidenav").style.width = "0";
              //document.getElementById("container").style.opacity = "1";
              //document.getElementById("container").style.backgroundColor = "transparent";
            }
            </script>
            <script src="https://vjs.zencdn.net/7.5.5/video.js"></script>
</body>
</html>

bopwebapi/posts/templates/posts/comment_form.html
{% extends 'posts/base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Comment</button>
    </form>
{% endblock %}

bopwebapi/posts/templates/posts/graph.html
{% extends 'posts/base.html' %}

{% block content %}
    
    <!-- <img src="{{ plt.url }}" alt="graph"> -->

{% endblock %}

bopwebapi/posts/templates/posts/index.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}
    <div>
        <h1>Bop!</h1>
    </div>
{% endblock %}

bopwebapi/posts/templates/posts/post_detail.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}
    <div class="post-detail-post">
        <!-- <img draggable="false" style="user-select: none;" src="{{ post.image.url }}" alt="Post Image"> -->
        <video controls width="800" height="450" src="{{ post.video.url }}"></video>
        <p style="transform: translateY(0.5rem);" class="post-list-description">{{ post.description }}</p>
        {% if request.user == post.author %}
        <a href="{% url 'posts:update-post' pk=post.pk %}">
            <button class="update-video-button" style="text-transform: capitalize; margin-top: 1rem;">update video</button>
        </a>
        {% else %}
        {% endif %}
        <p><img style="border-radius: 50%; transform: translateY(0.75rem);" class="profile-image-small-right-float" src="{{ post.author.profile.image.url }}" alt="profile image" height="40" width="40"><a style="margin-left: 0.75rem;" href="{% url 'users:view_profile_with_pk' pk=post.author.pk %}"><strong>{{ post.author }}</strong></p></a>
        {% if user in obj.subscribers.all %}
        <p style="margin-top: 1rem;">Unsubscribe</p>
        {% else %}
        <p style="margin-top: 1rem;">Subscribe</p>
        {% endif %}
    <div style="margin-top: 5rem ;" class="comment-detail-box">
        <p>Comments: {{ post.comments.count }}</p>
        <a class="add-comment-post-detail" href="{% url 'posts:add-comment' pk=post.pk %}"><p>Add comment</p></a>
        {% for comment in post.comments.all %}
            <p>{{ comment.text }}</p>
        {% endfor %}
    </div>
    </div>
{% endblock %}

bopwebapi/posts/templates/posts/post_form.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}
    <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Post!</button>
    </form>
{% endblock %}

bopwebapi/posts/templates/posts/post_list.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}

    <div class="posts-grid-posts-page">
    {% for post in posts %}
    
        <div class="post-div">
            <a href="{% url 'posts:post-detail' pk=post.pk %}">
            <!-- <img draggable="false" style="user-select: none;" src="{{ post.image.url }}" alt="Post Image"> -->
            
            <!-- <img src="{{ post.image.url }}" alt="Post image"> -->
            <!-- <video width="250" height="200" src="{{ post.video.url }}"></video> -->
            {% if post.thumbnail %}
            <div style="width: 250px; height: 200px; background-image: url({{ post.thumbnail.url }}); background-size: cover;" class="thumb" ></div>
            {% else %}
            <div style="width: 250px; height: 200px;" class="videocontainer thumb">
            <video style="width: 250px; height: 200px;" src="{{ post.video.url }}"></video>
            </div>
            <!-- <div style="width: 250px; height: 200px; background-image: url({{ post.video.url }}); background-size: cover;" class="thumb" ></div> -->
            {% endif %}
            
            <!--  -->
            <!-- <video width="250" height="200" src="{{ post.video.url }}"></video> -->
            </a>
            <p style="margin-top: 1rem;" class="post-list-description">{{ post.description }}</p>
            <p>Posted by <a href="{% url 'users:view_profile_with_pk' pk=post.author.pk %}"><strong>{{ post.author }}</strong></p></a>
        </div>
        
    {% endfor %}
    </div>

    

    <style>
        
    </style>
{% endblock %}

bopwebapi/posts/templates/posts/post_update.html
{% extends 'posts/base.html' %}
{% load static %}
{% block content %}
{% if request.user == post.author %}
    <h1>Update video</h1>
    
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Video</button>
    </form>
{% else %}
<div class="error-container">
<h1><i class="fas fa-exclamation-triangle"></i> Oops! Looks like you don't have access to this! Return to the <a href="{% url 'posts:posts' %}">homepage</a> or if you think this is an error, <a href="#">submit a bug report</a></h1>

</div>
<div style="margin-top: 50vh;" class="img-cont-cont">
<div style="margin: 0 auto; text-align: center; user-select: none;" class="img-cont">
<img  draggable="false" style="user-select: none;" height="85" width="auto" class="navbar-logo-header" src="{% static 'images/bop-logo.png' %}" alt="Bop's Logo">
<br>
<small style="font-family: 'Josefin Sans', sans-serif;">Copyright Bop&copy; 2019</small>
</div>
</div>
{% endif %}

{% endblock %}